stages:
  - test
  - build
  - deploy

variables:
  # set docker host to connect to docker in kubernetes
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  # TODO: Set correct certs dir to /certs according to this article: https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ""

cache:
  key: "lotta-schedule-provider-node-modules"
  paths:
    - node_modules/

test:
  stage: test
  image: node:12
  script:
    - npm install
    - npm run test

build docker image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n "$DOCKER_HUB_USER:$DOCKER_HUB_PASSWORD" | base64)\"}}}" > /kaniko/.docker/config.json
    - if [ $CI_COMMIT_REF_NAME == "develop" ];
        then /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination lotta/schedule-provider:$CI_COMMIT_SHA --destination lotta/schedule-provider:staging;
        elif [ $CI_COMMIT_REF_NAME == "master" ];
        then /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination lotta/schedule-provider:$CI_COMMIT_SHA --destination lotta/schedule-provider:stable --destination lotta/schedule-provider:latest;
        else /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination lotta/schedule-provider:$CI_COMMIT_SHA;
        fi

deploy:staging:
  stage: deploy
  environment:
    name: staging
  image:
    name: lotta/do-helm-deploy:latest
  script:
    - /user/local/bin/setup.sh
    - helm repo add lotta https://medienportal.gitlab.io/helm-charts
    - helm repo update
    - helm upgrade --install lotta-schedule-provider-staging lotta/lotta-schedule-provider
      --namespace lotta-staging --wait
      --set appEnvironment=staging
      --set image.tag=${CI_COMMIT_SHA}
      --set replicaCount=1
      --set honeybadger.enabled=true
      --set honeybadger.apiKey=$HONEYBADGER_API_KEY
    - curl -g "https://api.honeybadger.io/v1/deploys?deploy[environment]=staging&deploy[repository]=$CI_REPOSITORY_URL&deploy[revision]=$CI_COMMIT_SHA&api_key=$HONEYBADGER_API_KEY"
  only:
    refs:
      - develop

deploy:production:
  stage: deploy
  environment:
    name: production
  image:
    name: lotta/do-helm-deploy:latest
  script:
    - /user/local/bin/setup.sh
    - helm repo add lotta https://medienportal.gitlab.io/helm-charts
    - helm repo update
    - helm upgrade --install lotta-schedule-provider lotta/lotta-schedule-provider
      --set appEnvironment=production
      --namespace lotta --wait
      --set image.tag=${CI_COMMIT_SHA}
      --set replicaCount=2
      --set honeybadger.enabled=true
      --set honeybadger.apiKey=$HONEYBADGER_API_KEY
    - curl -g "https://api.honeybadger.io/v1/deploys?deploy[environment]=staging&deploy[repository]=$CI_REPOSITORY_URL&deploy[revision]=$CI_COMMIT_SHA&api_key=$HONEYBADGER_API_KEY"
  only:
    refs:
      - master
