name: "Tag docker container"

on:
  create:
    tags:
      - '*'

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Tag and push image
      run: |
        docker pull lotta/schedule-provider:$GITHUB_SHA
        docker tag lotta/schedule-provider:$GITHUB_SHA lotta/schedule-provider:$GITHUB_ENV
        docker push lotta/schedule-provider:$GITHUB_ENV
        docker tag lotta/schedule-provider:$GITHUB_SHA lotta/schedule-provider:latest
        docker push lotta/schedule-provider:latest
