name: "Push docker"

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
    
  push:
    if: github.event.pull_request.merged

    runs-on: ubuntu-latest
    
    steps:
    - name: Set env
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        fi;

    - name: Download built image
      if: github.event.pull_request.merged
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        workflow_conclusion: success
        name: docker-image
        path: artifact

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: load image from archive
      run: |
        docker load -i artifact/image.tar
        
    - name: push image to registry
      run: |
        docker tag lotta/schedule-provider lotta/schedule-provider:$GITHUB_SHA
        docker push lotta/schedule-provider:$GITHUB_SHA
        if [ -z "$RELEASE_VERSION" ]; then
          docker tag lotta/schedule-provider lotta/schedule-provider:develop
          docker push lotta/schedule-provider:develop
        else
          docker tag lotta/schedule-provider lotta/schedule-provider:$RELEASE_VERSION
          docker push lotta/schedule-provider:$RELEASE_VERSION
          docker push lotta/schedule-provider
        fi
